"""
tools/report_generator.py
--------------------------
Generates downloadable research reports from approved findings.
Supports: plain text (.txt) and PDF (.pdf) via fpdf2.
"""

import os
from datetime import datetime
from typing import List, Dict


def generate_text_report(
    title: str,
    sections: List[Dict],
    researcher_id: str = "",
    project_id: str = "",
) -> str:
    """
    Generates a plain-text research report.

    Args:
        title       : Report title
        sections    : List of {"heading": str, "content": str}
        researcher_id, project_id: Metadata

    Returns:
        Report as a string
    """
    now = datetime.now().strftime("%Y-%m-%d %H:%M")
    lines = [
        "=" * 70,
        f"  MEDISYN LABS — AI HEALTHCARE RESEARCH REPORT",
        f"  {title}",
        "=" * 70,
        f"  Researcher : {researcher_id}",
        f"  Project    : {project_id}",
        f"  Generated  : {now}",
        "=" * 70,
        "",
    ]
    for sec in sections:
        lines.append(f"\n{'─' * 60}")
        lines.append(f"  {sec.get('heading', 'Section').upper()}")
        lines.append(f"{'─' * 60}")
        lines.append(sec.get("content", ""))
        lines.append("")

    lines += [
        "=" * 70,
        "  DISCLAIMER: This report is generated by AI for research purposes only.",
        "  It does not constitute medical advice. Always consult qualified",
        "  healthcare professionals for clinical decisions.",
        "=" * 70,
    ]
    return "\n".join(lines)


def generate_pdf_report(
    title: str,
    sections: List[Dict],
    researcher_id: str = "",
    project_id: str = "",
    output_path: str = None,
) -> bytes:
    """
    Generates a PDF research report using fpdf2.

    Returns:
        PDF as bytes (for Streamlit download button)
    """
    try:
        from fpdf import FPDF

        class MediSynPDF(FPDF):
            def header(self):
                self.set_font("Helvetica", "B", 12)
                self.set_text_color(0, 80, 160)
                self.cell(0, 8, "MediSyn Labs — AI Healthcare Research Report", align="C", new_x="LMARGIN", new_y="NEXT")
                self.set_draw_color(0, 80, 160)
                self.line(10, self.get_y(), 200, self.get_y())
                self.ln(4)

            def footer(self):
                self.set_y(-15)
                self.set_font("Helvetica", "I", 8)
                self.set_text_color(128)
                self.cell(0, 10, f"Page {self.page_no()} | For research purposes only. Not medical advice.", align="C")

        pdf = MediSynPDF()
        pdf.add_page()
        pdf.set_margins(15, 20, 15)
        pdf.set_auto_page_break(auto=True, margin=20)

        # Title
        pdf.set_font("Helvetica", "B", 16)
        pdf.set_text_color(0, 0, 0)
        pdf.multi_cell(0, 10, title, align="C")
        pdf.ln(4)

        # Metadata
        pdf.set_font("Helvetica", "", 9)
        pdf.set_text_color(100, 100, 100)
        now = datetime.now().strftime("%Y-%m-%d %H:%M")
        pdf.cell(0, 6, f"Researcher: {researcher_id}  |  Project: {project_id}  |  Generated: {now}", new_x="LMARGIN", new_y="NEXT")
        pdf.ln(6)

        # Sections
        for sec in sections:
            heading = sec.get("heading", "Section")
            content = sec.get("content", "")

            # Section heading
            pdf.set_font("Helvetica", "B", 12)
            pdf.set_text_color(0, 80, 160)
            pdf.set_fill_color(235, 245, 255)
            pdf.cell(0, 8, f"  {heading}", fill=True, new_x="LMARGIN", new_y="NEXT")
            pdf.ln(2)

            # Section content
            pdf.set_font("Helvetica", "", 10)
            pdf.set_text_color(30, 30, 30)
            clean_content = content.replace("**", "").replace("##", "").replace("###", "").replace("#", "")
            pdf.multi_cell(0, 6, clean_content)
            pdf.ln(4)

        # Disclaimer
        pdf.set_font("Helvetica", "I", 8)
        pdf.set_text_color(150, 0, 0)
        pdf.multi_cell(0, 5, "DISCLAIMER: This report is AI-generated for research purposes only and does not constitute medical advice. Always consult qualified healthcare professionals for clinical decisions.")

        return bytes(pdf.output())

    except ImportError:
        # Fallback: return text as bytes
        text = generate_text_report(title, sections, researcher_id, project_id)
        return text.encode("utf-8")
    except Exception as e:
        text = f"PDF generation error: {str(e)}\n\n" + generate_text_report(title, sections, researcher_id, project_id)
        return text.encode("utf-8")
